//
//  BaseGrid.swift
//  DevDesign
//
//  Created by Sok Pich on 08/03/2026.
//
// Pure data + math. No UI dependencies.

import Foundation

// MARK: - Base Grid

enum BaseGrid: Double, CaseIterable, Identifiable {
    case four  = 4
    case eight = 8

    var id: Double { rawValue }

    var label: String {
        switch self {
        case .four:  return "4pt Grid"
        case .eight: return "8pt Grid"
        }
    }

    var description: String {
        switch self {
        case .four:  return "Fine-grained · Mobile UI standard"
        case .eight: return "Coarser · Desktop & layout spacing"
        }
    }
}

// MARK: - Spacing Token

struct SpacingToken: Identifiable, Equatable {
    let id: UUID
    var name: String            // e.g. "xs"
    var tokenName: String       // e.g. "spacingXS" — used in export
    var multiplier: Double      // e.g. 2.0 → value = base × 2
    var value: Double           // computed: base × multiplier
    var description: String     // e.g. "Icon gap, tight insets"
    var customValue: Double?    // non-nil when manually overridden

    var resolvedValue: Double { customValue ?? value }

    var isOverridden: Bool { customValue != nil }

    mutating func resetOverride() { customValue = nil }
}

// MARK: - Spacing Scale Engine

enum SpacingEngine {

    /// Default token definitions — multipliers relative to base grid unit.
    /// Value = base × multiplier.  At 4pt: xxs=2, xs=4, sm=8 … xxxl=80
    static let defaultTokens: [(name: String, token: String, multiplier: Double, description: String)] = [
        ("xxs",  "spacingXXS",  0.5,  "Hairline gap, tight chip padding"),
        ("xs",   "spacingXS",   1.0,  "Icon gap, badge inset"),
        ("sm",   "spacingSM",   2.0,  "Component inner padding"),
        ("md",   "spacingMD",   3.0,  "Card padding, form spacing"),
        ("lg",   "spacingLG",   4.0,  "Section gap, list row height"),
        ("xl",   "spacingXL",   6.0,  "Section separation"),
        ("xxl",  "spacingXXL",  8.0,  "Screen padding, page sections"),
        ("xxxl", "spacingXXXL", 10.0, "Hero spacing, splash padding"),
    ]

    static func generate(base: BaseGrid) -> [SpacingToken] {
        defaultTokens.map { meta in
            SpacingToken(
                id: UUID(),
                name: meta.name,
                tokenName: meta.token,
                multiplier: meta.multiplier,
                value: base.rawValue * meta.multiplier,
                description: meta.description
            )
        }
    }

    static func recompute(tokens: [SpacingToken], base: BaseGrid) -> [SpacingToken] {
        var updated = tokens
        for i in updated.indices {
            updated[i].value = base.rawValue * updated[i].multiplier
            // Preserve any custom overrides as-is
        }
        return updated
    }
}

// MARK: - Spacing Export Service

enum SpacingExportService {

    static func exportSwiftUI(_ tokens: [SpacingToken], base: BaseGrid) -> String {
        var lines = [
            "import SwiftUI",
            "",
            "// Generated by DevDesign — \(base.label)",
            "enum AppSpacing {",
            "",
        ]
        for t in tokens {
            let v = formatValue(t.resolvedValue)
            lines.append("    /// \(t.description)")
            lines.append("    static let \(t.name): CGFloat = \(v)")
        }
        lines += ["", "}"]
        return lines.joined(separator: "\n")
    }

    static func exportSwiftEnum(_ tokens: [SpacingToken], base: BaseGrid) -> String {
        var lines = [
            "// Generated by DevDesign — \(base.label)",
            "enum Spacing: CGFloat, CaseIterable {",
            "",
        ]
        for t in tokens {
            let v = formatValue(t.resolvedValue)
            lines.append("    /// \(t.description)")
            lines.append("    case \(t.name) = \(v)")
        }
        lines += ["", "}"]
        return lines.joined(separator: "\n")
    }

    static func exportCSS(_ tokens: [SpacingToken], base: BaseGrid) -> String {
        var lines = [
            "/* Generated by DevDesign — \(base.label) */",
            ":root {",
        ]
        for t in tokens {
            lines.append("  --spacing-\(t.name): \(formatValue(t.resolvedValue))px; /* \(t.description) */")
        }
        lines += ["}"]
        return lines.joined(separator: "\n")
    }

    static func exportJSON(_ tokens: [SpacingToken], base: BaseGrid) -> String {
        let dict: [String: Any] = [
            "generatedBy": "DevDesign",
            "baseGrid": base.rawValue,
            "unit": "pt",
            "tokens": tokens.map { t in
                [
                    "name": t.name,
                    "token": t.tokenName,
                    "multiplier": t.multiplier,
                    "value": t.resolvedValue,
                    "description": t.description,
                    "isOverridden": t.isOverridden
                ] as [String: Any]
            }
        ]
        guard let data = try? JSONSerialization.data(withJSONObject: dict, options: .prettyPrinted),
              let str = String(data: data, encoding: .utf8) else { return "{}" }
        return str
    }

    static func formatValue(_ v: Double) -> String {
        v.truncatingRemainder(dividingBy: 1) == 0
            ? String(format: "%.0f", v)
            : String(format: "%.1f", v)
    }
}
