//
//  TokenExportFormat.swift
//  DevDesign
//
//  Created by Sok Pich on 3/9/26.
//

import SwiftUI

// MARK: - Export Format

enum TokenExportFormat: String, CaseIterable, Identifiable {
    case swiftEnum  = "Swift"
    case json       = "JSON"
    case css        = "CSS"
    case all        = "All"

    var id: String { rawValue }
    var icon: String {
        switch self {
        case .swiftEnum: return "swift"
        case .json:      return "curlybraces"
        case .css:       return "globe"
        case .all:       return "doc.on.doc"
        }
    }
    var fileExtension: String {
        switch self {
        case .swiftEnum: return ".swift"
        case .json:      return ".json"
        case .css:       return ".css"
        case .all:       return ".txt"
        }
    }
}

// MARK: - Token Section

enum TokenSection: String, CaseIterable, Identifiable {
    case colors     = "Colors"
    case typography = "Typography"
    case spacing    = "Spacing"
    case export     = "Export"

    var id: String { rawValue }
    var icon: String {
        switch self {
        case .colors:     return "paintpalette"
        case .typography: return "textformat"
        case .spacing:    return "ruler"
        case .export:     return "square.and.arrow.up"
        }
    }
}

// MARK: - Color Token

struct ColorToken: Identifiable, Equatable {
    let id: UUID
    var tokenName: String       // camelCase, used in export
    var hex: String             // e.g. "#7B6EF6"
    var label: String           // human display label (from SavedColor.label if set)
    var paletteName: String     // which palette it came from
    var paletteId: UUID
    var red: Double
    var green: Double
    var blue: Double
    var alpha: Double

    var color: Color { Color(red: red, green: green, blue: blue, opacity: alpha) }

    // token path: colors.paletteName.tokenName
    var path: String {
        let safe = DesignTokenExportService.safeName(paletteName)
        return "colors.\(safe).\(tokenName)"
    }

    // W3C Design Token type
    static let w3cType = "color"
}

// MARK: - Typography Token

struct TypographyToken: Identifiable, Equatable {
    let id: UUID
    var tokenName: String       // e.g. "displayLarge"
    var name: String            // e.g. "Display"
    var size: Double
    var lineHeight: Double      // multiplier
    var tracking: Double        // em
    var weightRaw: String       // e.g. "semibold"

    var fontWeight: Font.Weight {
        switch weightRaw {
        case "ultraLight": return .ultraLight
        case "thin":       return .thin
        case "light":      return .light
        case "regular":    return .regular
        case "medium":     return .medium
        case "semibold":   return .semibold
        case "bold":       return .bold
        case "heavy":      return .heavy
        case "black":      return .black
        default:           return .regular
        }
    }

    var lineHeightPt: Double { (size * lineHeight).rounded(.toNearestOrAwayFromZero) }
    var trackingPt: Double   { (tracking * size * 1000).rounded() / 1000 }
}

// MARK: - Spacing Token (wrapper — re-exported from SpacingModels)

struct SpacingDesignToken: Identifiable, Equatable {
    let id: UUID
    var tokenName: String      // e.g. "spacingMD"
    var name: String           // e.g. "md"
    var value: Double          // pt
    var description: String
}

// MARK: - Token Set (the aggregate)

struct DesignTokenSet {
    var colors: [ColorToken]
    var typography: [TypographyToken]
    var spacing: [SpacingDesignToken]

    var isEmpty: Bool { colors.isEmpty && typography.isEmpty && spacing.isEmpty }
}

// MARK: - Export Service

enum DesignTokenExportService {

    // MARK: - Swift Enum

    static func exportSwift(_ set: DesignTokenSet,
                             includeColors: Bool,
                             includeTypography: Bool,
                             includeSpacing: Bool) -> String {
        var lines: [String] = []
        lines.append("// DesignTokens.swift")
        lines.append("// Auto-generated by DevDesign")
        lines.append("import SwiftUI")
        lines.append("")
        lines.append("enum DesignTokens {")

        if includeColors && !set.colors.isEmpty {
            lines.append("")
            lines.append("    // MARK: - Colors")
            // Group by palette
            let grouped = Dictionary(grouping: set.colors, by: \.paletteName)
            let sortedPalettes = grouped.keys.sorted()
            lines.append("    enum Colors {")
            for palette in sortedPalettes {
                let tokens = grouped[palette]!
                lines.append("")
                lines.append("        // \(palette)")
                lines.append("        enum \(swiftTypeName(palette)) {")
                for token in tokens {
                    let r = f(token.red); let g = f(token.green)
                    let b = f(token.blue); let a = f(token.alpha)
                    lines.append("            /// \(token.hex)")
                    if token.alpha < 1 {
                        lines.append("            static let \(token.tokenName) = Color(red: \(r), green: \(g), blue: \(b)).opacity(\(a))")
                    } else {
                        lines.append("            static let \(token.tokenName) = Color(hex: \"\(token.hex)\")")
                    }
                }
                lines.append("        }")
            }
            lines.append("    }")
        }

        if includeTypography && !set.typography.isEmpty {
            lines.append("")
            lines.append("    // MARK: - Typography")
            lines.append("    enum Typography {")
            lines.append("        struct TypeStyle {")
            lines.append("            let size: CGFloat")
            lines.append("            let lineHeight: CGFloat")
            lines.append("            let tracking: CGFloat")
            lines.append("            let weight: Font.Weight")
            lines.append("            var font: Font { .system(size: size, weight: weight) }")
            lines.append("        }")
            lines.append("")
            for t in set.typography {
                lines.append("        /// \(t.name) — \(Int(t.size))pt \(t.weightRaw)")
                lines.append("        static let \(t.tokenName) = TypeStyle(")
                lines.append("            size: \(f(t.size)),")
                lines.append("            lineHeight: \(f(t.lineHeightPt)),")
                lines.append("            tracking: \(f3(t.trackingPt)),")
                lines.append("            weight: .\(t.weightRaw)")
                lines.append("        )")
            }
            lines.append("    }")
        }

        if includeSpacing && !set.spacing.isEmpty {
            lines.append("")
            lines.append("    // MARK: - Spacing")
            lines.append("    enum Spacing {")
            for s in set.spacing {
                lines.append("        /// \(s.description)")
                lines.append("        static let \(s.tokenName): CGFloat = \(f(s.value))")
            }
            lines.append("    }")
        }

        lines.append("}")
        return lines.joined(separator: "\n")
    }

    // MARK: - JSON (W3C Design Token Community Group format)

    static func exportJSON(_ set: DesignTokenSet,
                            includeColors: Bool,
                            includeTypography: Bool,
                            includeSpacing: Bool) -> String {
        var root: [String: Any] = [:]

        if includeColors && !set.colors.isEmpty {
            var colorsNode: [String: Any] = [:]
            let grouped = Dictionary(grouping: set.colors, by: \.paletteName)
            for (palette, tokens) in grouped.sorted(by: { $0.key < $1.key }) {
                var paletteNode: [String: Any] = [:]
                for token in tokens {
                    paletteNode[token.tokenName] = [
                        "$type": "color",
                        "$value": token.hex,
                        "$description": token.label.isEmpty ? token.hex : token.label
                    ]
                }
                colorsNode[safeName(palette)] = paletteNode
            }
            root["colors"] = colorsNode
        }

        if includeTypography && !set.typography.isEmpty {
            var typeNode: [String: Any] = [:]
            for t in set.typography {
                typeNode[t.tokenName] = [
                    "$type": "typography",
                    "$value": [
                        "fontFamily": "SF Pro",
                        "fontSize": "\(Int(t.size))pt",
                        "fontWeight": t.weightRaw,
                        "lineHeight": "\(Int(t.lineHeightPt))pt",
                        "letterSpacing": String(format: "%.3f", t.tracking)
                    ],
                    "$description": t.name
                ]
            }
            root["typography"] = typeNode
        }

        if includeSpacing && !set.spacing.isEmpty {
            var spacingNode: [String: Any] = [:]
            for s in set.spacing {
                spacingNode[s.tokenName] = [
                    "$type": "dimension",
                    "$value": "\(Int(s.value))pt",
                    "$description": s.description
                ]
            }
            root["spacing"] = spacingNode
        }

        return prettyJSON(root)
    }

    // MARK: - CSS Custom Properties

    static func exportCSS(_ set: DesignTokenSet,
                           includeColors: Bool,
                           includeTypography: Bool,
                           includeSpacing: Bool) -> String {
        var lines: [String] = []
        lines.append("/* Design Tokens — Auto-generated by DevDesign */")
        lines.append(":root {")

        if includeColors && !set.colors.isEmpty {
            lines.append("")
            lines.append("  /* ── Colors ── */")
            let grouped = Dictionary(grouping: set.colors, by: \.paletteName)
            for palette in grouped.keys.sorted() {
                lines.append("  /* \(palette) */")
                for token in grouped[palette]! {
                    let cssName = "--color-\(kebab(token.tokenName))"
                    if token.alpha < 1 {
                        let r = Int(token.red * 255)
                        let g = Int(token.green * 255)
                        let b = Int(token.blue * 255)
                        lines.append("  \(cssName): rgba(\(r), \(g), \(b), \(f(token.alpha)));")
                    } else {
                        lines.append("  \(cssName): \(token.hex);")
                    }
                }
            }
        }

        if includeTypography && !set.typography.isEmpty {
            lines.append("")
            lines.append("  /* ── Typography ── */")
            for t in set.typography {
                let prefix = "--type-\(kebab(t.tokenName))"
                lines.append("  \(prefix)-size: \(Int(t.size))pt;")
                lines.append("  \(prefix)-line-height: \(Int(t.lineHeightPt))pt;")
                lines.append("  \(prefix)-weight: \(cssWeight(t.weightRaw));")
                if abs(t.trackingPt) > 0.001 {
                    lines.append("  \(prefix)-letter-spacing: \(String(format: "%.3f", t.trackingPt))pt;")
                }
            }
        }

        if includeSpacing && !set.spacing.isEmpty {
            lines.append("")
            lines.append("  /* ── Spacing ── */")
            for s in set.spacing {
                lines.append("  --spacing-\(s.name): \(Int(s.value))pt; /* \(s.description) */")
            }
        }

        lines.append("}")
        return lines.joined(separator: "\n")
    }

    // MARK: - Helpers

    static func safeName(_ raw: String) -> String {
        let cleaned = raw.components(separatedBy: .whitespacesAndNewlines).joined()
        return cleaned.isEmpty ? "unnamed" : cleaned.prefix(1).lowercased() + cleaned.dropFirst()
    }

    static func swiftTypeName(_ raw: String) -> String {
        let words = raw.components(separatedBy: CharacterSet.alphanumerics.inverted)
        return words.map { $0.prefix(1).uppercased() + $0.dropFirst() }.joined()
    }

    static func kebab(_ camel: String) -> String {
        var result = ""
        for (i, char) in camel.enumerated() {
            if char.isUppercase && i > 0 { result.append("-") }
            result.append(char.lowercased())
        }
        return result
    }

    static func cssWeight(_ w: String) -> String {
        switch w {
        case "ultraLight": return "100"
        case "thin":       return "200"
        case "light":      return "300"
        case "regular":    return "400"
        case "medium":     return "500"
        case "semibold":   return "600"
        case "bold":       return "700"
        case "heavy":      return "800"
        case "black":      return "900"
        default:           return "400"
        }
    }

    static func f(_ v: Double) -> String {
        v.truncatingRemainder(dividingBy: 1) == 0
            ? String(format: "%.0f", v)
            : String(format: "%.2f", v)
    }

    static func f3(_ v: Double) -> String {
        String(format: "%.3f", v)
    }

    // Simple recursive JSON pretty-printer (no JSONSerialization to avoid Foundation Data)
    private static func prettyJSON(_ value: Any, indent: Int = 0) -> String {
        let pad  = String(repeating: "  ", count: indent)
        let pad1 = String(repeating: "  ", count: indent + 1)
        if let dict = value as? [String: Any] {
            if dict.isEmpty { return "{}" }
            let pairs = dict.keys.sorted().map { key -> String in
                "\(pad1)\"\(key)\": \(prettyJSON(dict[key]!, indent: indent + 1))"
            }
            return "{\n\(pairs.joined(separator: ",\n"))\n\(pad)}"
        } else if let arr = value as? [Any] {
            if arr.isEmpty { return "[]" }
            let items = arr.map { prettyJSON($0, indent: indent + 1) }
            return "[\n\(items.map { "\(pad1)\($0)" }.joined(separator: ",\n"))\n\(pad)]"
        } else if let str = value as? String {
            return "\"\(str.replacingOccurrences(of: "\"", with: "\\\""))\""
        } else if let int = value as? Int {
            return "\(int)"
        } else if let dbl = value as? Double {
            return f(dbl)
        } else if let bool = value as? Bool {
            return bool ? "true" : "false"
        }
        return "null"
    }

    // MARK: - Auto-generate token name from hex + index

    static func tokenName(from label: String, hex: String, index: Int) -> String {
        if !label.trimmingCharacters(in: .whitespaces).isEmpty {
            // camelCase from label
            let words = label.components(separatedBy: CharacterSet.alphanumerics.inverted)
                .filter { !$0.isEmpty }
            guard !words.isEmpty else { return "color\(index)" }
            let first = words[0].lowercased()
            let rest  = words.dropFirst().map { $0.prefix(1).uppercased() + $0.dropFirst().lowercased() }
            return ([first] + rest).joined()
        }
        // Fallback: "color" + short hex
        let short = hex.replacingOccurrences(of: "#", with: "").prefix(4).lowercased()
        return "color\(short)\(index)"
    }
}
